apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default  # or any other namespace you are using
spec:
  replicas: 3  # adjust the number of replicas as needed
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: us-phoenix-1.ocir.io/oracleamerica/cicd-microservices:${GITHUB_SHA}  # replace with your actual image path
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
