name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: us-phoenix-1.ocir.io/oracleamerica/cicd-microservices:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.29.1'

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/deployment.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
