name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t us-phoenix-1.ocir.io/oracleamerica/cicd-microservices:${{ github.sha }} .

      - name: Login to OCIR
        run: echo "${{ secrets.OCIR_PASSWORD }}" | docker login -u "${{ secrets.OCIR_USERNAME }}" --password-stdin us-phoenix-1.ocir.io/oracleamerica/cicd-microservices

      - name: Push Docker image to OCIR
        run: docker push us-phoenix-1.ocir.io/oracleamerica/cicd-microservices:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.1

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy to OKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl set image deployment/my-deployment my-container=us-phoenix-1.ocir.io/oracleamerica/kubectl:${{ github.sha }}
