name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t us-phoenix-1.ocir.io/oracleamerica/cicd-microservices:${{ github.sha }} .

      - name: Login to OCIR
        run: echo "${{ secrets.OCIR_PASSWORD }}" | docker login -u "${{ secrets.OCIR_USERNAME }}" --password-stdin us-phoenix-1.ocir.io/oracleamerica/cicd-microservices

      - name: Push Docker image to OCIR
        run: docker push us-phoenix-1.ocir.io/oracleamerica/cicd-microservices:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.29.1/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install OCI CLI
        run: |
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
      # Ensure the PATH is updated for subsequent steps
      - name: Update PATH
        run: echo 'export PATH=$PATH:$HOME/bin' >> $GITHUB_ENV

      - name: Configure OCI CLI
        run: |
          mkdir -p $HOME/.oci
          echo "${{ secrets.OCI_CLI_CONFIG }}" > $HOME/.oci/config
          echo "${{ secrets.OCI_CLI_KEY }}" > $HOME/.oci/oci_api_key.pem
        env:
          OCI_CLI_CONFIG: $HOME/.oci/config
          OCI_CLI_KEY: $HOME/.oci/oci_api_key.pem

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Configure Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Verify kubectl and OCI CLI
        run: |
          kubectl version --client
          oci --version

      - name: Deploy to OKE
        run: |
          kubectl set image deployment/my-deployment my-container=us-phoenix-1.ocir.io/oracleamerica/cicd-microservices:${{ github.sha }}
